### ISSUE TITLE
Doesn't launch

### ISSUE THREAD

**Issue by rowbawts** [flathub/net.gaijin.WarThunder#12]
Everytime I try to run the Flatpak I get this error 

`cp: cannot create regular file '/var/home/seby/.var/app/net.gaijin.WarThunder/data/WarThunder/version': No such file or directory`

And I've tried fully re-installing by uninstalling with --delete-data.

**Comment by Doomsdayrs** [comment]
> Everytime I try to run the Flatpak I get this error
> 
> `cp: cannot create regular file '/var/home/seby/.var/app/net.gaijin.WarThunder/data/WarThunder/version': No such file or directory`
> 
> And I've tried fully re-installing by uninstalling with --delete-data.

Most intriguing of an issue. When I get home I will test to see why this is occurring

**Comment by Doomsdayrs** [comment]
Fixed with 5b3ff6b
