### ISSUE TITLE
Removing the app doesn't remove the games files

### ISSUE THREAD

**Issue by RotaryBoot58** [flathub/net.gaijin.WarThunder#145]
After uninstalling the flatpak app i noticed that the game files are not removed from the system and they are just taking disk space

**Comment by Doomsdayrs** [comment]
Good evening,

I had not thought of this shortcoming previously, and I have taken the motivation to question on the flatpak matrix chat in regards to a script to allow an app to cleanup its data directory.

I apologize for any grievances you have experienced, and if useful, you can remove it by heading into the `~/.var/app` directory and manually deleting WarThunder from there.

**Comment by RotaryBoot58** [comment]
That solved the issue, hope the flatpak team help you

**Comment by Doomsdayrs** [comment]
Uh, this is not solved though
