### ISSUE TITLE
The gamescope instructions are a bit unclear and misleading

### ISSUE THREAD

**Issue by user1-github** [flathub/net.gaijin.WarThunder#188]
After I installed WT, set my gamescope arguments and launched it, I've noticed that the launcher still displayed some non-native resolution. Then I realised that the Flatpak didn't automatically install the gamescope extension - this should be mentioned to be more clear for new users.

Also, your instructions in readme currently point to the wrong gamescope runtime:
com.valvesoftware.Steam.Utility.gamescope

but the correct one should be:
org.freedesktop.Platform.VulkanLayer.gamescope
according to your latest commit.

**Comment by Doomsdayrs** [comment]
Oops! Sorry! Will fix soon hopefully

**Comment by Doomsdayrs** [comment]
Fixed~
