### ISSUE TITLE
Problem installing war thunder via flathub.

### ISSUE THREAD

**Issue by ymmsmmsm** [flathub/net.gaijin.WarThunder#194]
![Screenshot 2024-01-09 21 06 19](https://github.com/flathub/net.gaijin.WarThunder/assets/92523537/e87b99ef-82a8-471a-9aa6-36b9b58cdc28)

`HI had a problem installing war thunder via flathub. When I wanted to insert the first command I just got the error`

**Comment by hfiguiere** [comment]
Likely fixed by #193
